config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end

  # :defaults => { :format => :json } 指定响应的默认格式
  # namespace :api, :defaults => { :format => :json } do
  # end

  # (:locale)，放在括号中，表示这个是可选的
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get 'who_bought', on: :member
    end
    get 'store/index'
    root 'store#index', :as => 'store'
  end

  # resource :posts, shallow: true do
  #   resources :reviews
  # end
end

# == Route Map
#
#             Prefix Verb   URI Pattern                                  Controller#Action
#              admin GET    /admin(.:format)                             admin#index
#              login GET    /login(.:format)                             sessions#new
#                    POST   /login(.:format)                             sessions#create
#             logout DELETE /logout(.:format)                            sessions#destroy
#              users GET    (/:locale)/users(.:format)                   users#index
#                    POST   (/:locale)/users(.:format)                   users#create
#           new_user GET    (/:locale)/users/new(.:format)               users#new
#          edit_user GET    (/:locale)/users/:id/edit(.:format)          users#edit
#               user GET    (/:locale)/users/:id(.:format)               users#show
#                    PATCH  (/:locale)/users/:id(.:format)               users#update
#                    PUT    (/:locale)/users/:id(.:format)               users#update
#                    DELETE (/:locale)/users/:id(.:format)               users#destroy
#             orders GET    (/:locale)/orders(.:format)                  orders#index
#                    POST   (/:locale)/orders(.:format)                  orders#create
#          new_order GET    (/:locale)/orders/new(.:format)              orders#new
#         edit_order GET    (/:locale)/orders/:id/edit(.:format)         orders#edit
#              order GET    (/:locale)/orders/:id(.:format)              orders#show
#                    PATCH  (/:locale)/orders/:id(.:format)              orders#update
#                    PUT    (/:locale)/orders/:id(.:format)              orders#update
#                    DELETE (/:locale)/orders/:id(.:format)              orders#destroy
#         line_items GET    (/:locale)/line_items(.:format)              line_items#index
#                    POST   (/:locale)/line_items(.:format)              line_items#create
#      new_line_item GET    (/:locale)/line_items/new(.:format)          line_items#new
#     edit_line_item GET    (/:locale)/line_items/:id/edit(.:format)     line_items#edit
#          line_item GET    (/:locale)/line_items/:id(.:format)          line_items#show
#                    PATCH  (/:locale)/line_items/:id(.:format)          line_items#update
#                    PUT    (/:locale)/line_items/:id(.:format)          line_items#update
#                    DELETE (/:locale)/line_items/:id(.:format)          line_items#destroy
#              carts GET    (/:locale)/carts(.:format)                   carts#index
#                    POST   (/:locale)/carts(.:format)                   carts#create
#           new_cart GET    (/:locale)/carts/new(.:format)               carts#new
#          edit_cart GET    (/:locale)/carts/:id/edit(.:format)          carts#edit
#               cart GET    (/:locale)/carts/:id(.:format)               carts#show
#                    PATCH  (/:locale)/carts/:id(.:format)               carts#update
#                    PUT    (/:locale)/carts/:id(.:format)               carts#update
#                    DELETE (/:locale)/carts/:id(.:format)               carts#destroy
# who_bought_product GET    (/:locale)/products/:id/who_bought(.:format) products#who_bought
#           products GET    (/:locale)/products(.:format)                products#index
#                    POST   (/:locale)/products(.:format)                products#create
#        new_product GET    (/:locale)/products/new(.:format)            products#new
#       edit_product GET    (/:locale)/products/:id/edit(.:format)       products#edit
#            product GET    (/:locale)/products/:id(.:format)            products#show
#                    PATCH  (/:locale)/products/:id(.:format)            products#update
#                    PUT    (/:locale)/products/:id(.:format)            products#update
#                    DELETE (/:locale)/products/:id(.:format)            products#destroy
#        store_index GET    (/:locale)/store/index(.:format)             store#index
#              store GET    /(:locale)(.:format)                         store#index
#

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    product = Product.find(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id, :price => product.price)
    end
    current_item
  end

  def total_price
    line_items.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update]
  skip_before_action :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Your cart is currently empty' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title"><%= t('.title') %></div>

<table class="cart">
  <%= render cart.line_items %>

  <tr class="total_line">
    <td colspan="3">Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
    <td></td>
  </tr>
</table>


<%= button_to t('.checkout'), new_order_path, :method => :get, :disabled => @order.present?? true : false, class: 'button_to' %>
<%= button_to t('.empty'), cart, method: :delete, remote: true, class: 'button_to' %>

app/views/carts/_form.html.erb
<!-- :local - By default form submits are remote and unobstrusive XHRs. Disable remote submits with local: true. -->

<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$("#cart").hide('blind', {  } , 500);

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>