config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end

  # :defaults => { :format => :json } 指定响应的默认格式
  # namespace :api, :defaults => { :format => :json } do
  # end

  # (:locale)，放在括号中，表示这个是可选的
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get 'who_bought', on: :member
    end
    get 'store/index'
    root 'store#index', :as => 'store'
  end

  # resource :posts, shallow: true do
  #   resources :reviews
  # end
end

# == Route Map
#
#             Prefix Verb   URI Pattern                                  Controller#Action
#              admin GET    /admin(.:format)                             admin#index
#              login GET    /login(.:format)                             sessions#new
#                    POST   /login(.:format)                             sessions#create
#             logout DELETE /logout(.:format)                            sessions#destroy
#              users GET    (/:locale)/users(.:format)                   users#index
#                    POST   (/:locale)/users(.:format)                   users#create
#           new_user GET    (/:locale)/users/new(.:format)               users#new
#          edit_user GET    (/:locale)/users/:id/edit(.:format)          users#edit
#               user GET    (/:locale)/users/:id(.:format)               users#show
#                    PATCH  (/:locale)/users/:id(.:format)               users#update
#                    PUT    (/:locale)/users/:id(.:format)               users#update
#                    DELETE (/:locale)/users/:id(.:format)               users#destroy
#             orders GET    (/:locale)/orders(.:format)                  orders#index
#                    POST   (/:locale)/orders(.:format)                  orders#create
#          new_order GET    (/:locale)/orders/new(.:format)              orders#new
#         edit_order GET    (/:locale)/orders/:id/edit(.:format)         orders#edit
#              order GET    (/:locale)/orders/:id(.:format)              orders#show
#                    PATCH  (/:locale)/orders/:id(.:format)              orders#update
#                    PUT    (/:locale)/orders/:id(.:format)              orders#update
#                    DELETE (/:locale)/orders/:id(.:format)              orders#destroy
#         line_items GET    (/:locale)/line_items(.:format)              line_items#index
#                    POST   (/:locale)/line_items(.:format)              line_items#create
#      new_line_item GET    (/:locale)/line_items/new(.:format)          line_items#new
#     edit_line_item GET    (/:locale)/line_items/:id/edit(.:format)     line_items#edit
#          line_item GET    (/:locale)/line_items/:id(.:format)          line_items#show
#                    PATCH  (/:locale)/line_items/:id(.:format)          line_items#update
#                    PUT    (/:locale)/line_items/:id(.:format)          line_items#update
#                    DELETE (/:locale)/line_items/:id(.:format)          line_items#destroy
#              carts GET    (/:locale)/carts(.:format)                   carts#index
#                    POST   (/:locale)/carts(.:format)                   carts#create
#           new_cart GET    (/:locale)/carts/new(.:format)               carts#new
#          edit_cart GET    (/:locale)/carts/:id/edit(.:format)          carts#edit
#               cart GET    (/:locale)/carts/:id(.:format)               carts#show
#                    PATCH  (/:locale)/carts/:id(.:format)               carts#update
#                    PUT    (/:locale)/carts/:id(.:format)               carts#update
#                    DELETE (/:locale)/carts/:id(.:format)               carts#destroy
# who_bought_product GET    (/:locale)/products/:id/who_bought(.:format) products#who_bought
#           products GET    (/:locale)/products(.:format)                products#index
#                    POST   (/:locale)/products(.:format)                products#create
#        new_product GET    (/:locale)/products/new(.:format)            products#new
#       edit_product GET    (/:locale)/products/:id/edit(.:format)       products#edit
#            product GET    (/:locale)/products/:id(.:format)            products#show
#                    PATCH  (/:locale)/products/:id(.:format)            products#update
#                    PUT    (/:locale)/products/:id(.:format)            products#update
#                    DELETE (/:locale)/products/:id(.:format)            products#destroy
#        store_index GET    (/:locale)/store/index(.:format)             store#index
#              store GET    /(:locale)(.:format)                         store#index
#

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  price       :decimal(8, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  default_scope { order(title: :asc) }
  has_many :line_items
  has_many :orders, :through => :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with => %r{\.(gif|jpg|png)$}i,
    :multiline => true,       # $ end of line
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }

  # If a method is private in Ruby, then it cannot be called by an
  # explicit receiver (object). It can only be call implicitly. It can
  # be called implicitly by the class in which it has been described in
  # as well as by the subclasses of this class.
  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'Line Items present')
        throw :abort
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :who_bought]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    if @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to products_url, notice: "#{@product.errors[:base].join("\n")}" }
        format.json { head :no_content }
      end
    end
  end

  def who_bought
    respond_to do |format|
      format.html
      format.atom
      format.json { render json: @product.orders }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, rows: 6 %>
  </div>
  
  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
  <h1>Listing Products</h1>

  <table>
    <tbody>
      <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag product.image_url, class: 'list_image' %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= product.title %></dt>
            <dt><%= truncate(strip_tags(product.description), length: 80) %></dt>
            <dt><%= product.price %></dt>
          </dl>
        </td>
        <td class="list_actions">
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/who_bought.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay_type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product.orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= simple_format order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>