config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end

  # :defaults => { :format => :json } 指定响应的默认格式
  # namespace :api, :defaults => { :format => :json } do
  # end

  # (:locale)，放在括号中，表示这个是可选的
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get 'who_bought', on: :member
    end
    get 'store/index'
    root 'store#index', :as => 'store'
  end

  # resource :posts, shallow: true do
  #   resources :reviews
  # end
end

# == Route Map
#
#             Prefix Verb   URI Pattern                                  Controller#Action
#              admin GET    /admin(.:format)                             admin#index
#              login GET    /login(.:format)                             sessions#new
#                    POST   /login(.:format)                             sessions#create
#             logout DELETE /logout(.:format)                            sessions#destroy
#              users GET    (/:locale)/users(.:format)                   users#index
#                    POST   (/:locale)/users(.:format)                   users#create
#           new_user GET    (/:locale)/users/new(.:format)               users#new
#          edit_user GET    (/:locale)/users/:id/edit(.:format)          users#edit
#               user GET    (/:locale)/users/:id(.:format)               users#show
#                    PATCH  (/:locale)/users/:id(.:format)               users#update
#                    PUT    (/:locale)/users/:id(.:format)               users#update
#                    DELETE (/:locale)/users/:id(.:format)               users#destroy
#             orders GET    (/:locale)/orders(.:format)                  orders#index
#                    POST   (/:locale)/orders(.:format)                  orders#create
#          new_order GET    (/:locale)/orders/new(.:format)              orders#new
#         edit_order GET    (/:locale)/orders/:id/edit(.:format)         orders#edit
#              order GET    (/:locale)/orders/:id(.:format)              orders#show
#                    PATCH  (/:locale)/orders/:id(.:format)              orders#update
#                    PUT    (/:locale)/orders/:id(.:format)              orders#update
#                    DELETE (/:locale)/orders/:id(.:format)              orders#destroy
#         line_items GET    (/:locale)/line_items(.:format)              line_items#index
#                    POST   (/:locale)/line_items(.:format)              line_items#create
#      new_line_item GET    (/:locale)/line_items/new(.:format)          line_items#new
#     edit_line_item GET    (/:locale)/line_items/:id/edit(.:format)     line_items#edit
#          line_item GET    (/:locale)/line_items/:id(.:format)          line_items#show
#                    PATCH  (/:locale)/line_items/:id(.:format)          line_items#update
#                    PUT    (/:locale)/line_items/:id(.:format)          line_items#update
#                    DELETE (/:locale)/line_items/:id(.:format)          line_items#destroy
#              carts GET    (/:locale)/carts(.:format)                   carts#index
#                    POST   (/:locale)/carts(.:format)                   carts#create
#           new_cart GET    (/:locale)/carts/new(.:format)               carts#new
#          edit_cart GET    (/:locale)/carts/:id/edit(.:format)          carts#edit
#               cart GET    (/:locale)/carts/:id(.:format)               carts#show
#                    PATCH  (/:locale)/carts/:id(.:format)               carts#update
#                    PUT    (/:locale)/carts/:id(.:format)               carts#update
#                    DELETE (/:locale)/carts/:id(.:format)               carts#destroy
# who_bought_product GET    (/:locale)/products/:id/who_bought(.:format) products#who_bought
#           products GET    (/:locale)/products(.:format)                products#index
#                    POST   (/:locale)/products(.:format)                products#create
#        new_product GET    (/:locale)/products/new(.:format)            products#new
#       edit_product GET    (/:locale)/products/:id/edit(.:format)       products#edit
#            product GET    (/:locale)/products/:id(.:format)            products#show
#                    PATCH  (/:locale)/products/:id(.:format)            products#update
#                    PUT    (/:locale)/products/:id(.:format)            products#update
#                    DELETE (/:locale)/products/:id(.:format)            products#destroy
#        store_index GET    (/:locale)/store/index(.:format)             store#index
#              store GET    /(:locale)(.:format)                         store#index
#

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default(1)
#  order_id   :integer
#  price      :decimal(8, 2)
#

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: :create 

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        session[:counter] = 0
        format.html { redirect_to store_url }
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    @cart = current_cart
    respond_to do |format|
      if params[:reduce]
        if @line_item.quantity > 1
          @line_item.quantity -= 1
          @line_item.save
        else
          @line_item.destroy
        end
        format.html { redirect_to store_url, notice: 'Line item was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @line_item }
      elsif @line_item.update(line_item_params)
        format.html { redirect_to store_url, notice: 'Line item was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @cart = current_cart
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to store_url, notice: 'Line item was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :line_item_product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.number_field :cart_id, id: :line_item_cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
  <td class="item_image"><%= image_tag line_item.product.image_url %></td>
  <td><%= link_to '⬇︎', line_item_path(line_item, reduce: true), method: :patch, remote: true, style: 'color: white' %></td>
  <td><%= line_item.quantity %>&times;</td>
  <td><%= line_item.product.title %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
  <td><%= link_to 'delete', line_item_path(line_item), method: :delete, remote: true %></td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
            line_item.quantity,
            truncate(line_item.product.title, :length => 50)) %>

app/views/line_items/create.js.erb
// $('#cart').html("<%=j render :partial => "carts/cart", :locals => { :cart => @cart } %>")
<% if @cart.total_items == 1 %>
  // hide flash[:notice] message in store index page
  $('#notice').hide();
  // add blind effect to cart when first add product to cart
  $('#cart').html("<%=j render @cart %>").hide();
  $("#cart").show('blind', {  } , 500);
<% else %>
  $('#cart').html("<%=j render @cart %>")
<% end %>
$('#current_item').effect("highlight", {color: '#DFF2BF'}, 1500);
$('#counter').html("");

app/views/line_items/destroy.js.erb
<% if @cart.total_items != 0 %>
  $('#cart').html('<%=j render @cart %>');
<% else %>
  $("#cart").hide('blind', {  } , 500);
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/update.js.erb
<% if @cart.total_items != 0 %>
  $('#cart').html('<%=j render @cart %>');
<% else %>
  $("#cart").hide('blind', {  } , 500);
<% end %>