config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end

  # :defaults => { :format => :json } 指定响应的默认格式
  # namespace :api, :defaults => { :format => :json } do
  # end

  # (:locale)，放在括号中，表示这个是可选的
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get 'who_bought', on: :member
    end
    get 'store/index'
    root 'store#index', :as => 'store'
  end

  # resource :posts, shallow: true do
  #   resources :reviews
  # end
end

# == Route Map
#
#             Prefix Verb   URI Pattern                                  Controller#Action
#              admin GET    /admin(.:format)                             admin#index
#              login GET    /login(.:format)                             sessions#new
#                    POST   /login(.:format)                             sessions#create
#             logout DELETE /logout(.:format)                            sessions#destroy
#              users GET    (/:locale)/users(.:format)                   users#index
#                    POST   (/:locale)/users(.:format)                   users#create
#           new_user GET    (/:locale)/users/new(.:format)               users#new
#          edit_user GET    (/:locale)/users/:id/edit(.:format)          users#edit
#               user GET    (/:locale)/users/:id(.:format)               users#show
#                    PATCH  (/:locale)/users/:id(.:format)               users#update
#                    PUT    (/:locale)/users/:id(.:format)               users#update
#                    DELETE (/:locale)/users/:id(.:format)               users#destroy
#             orders GET    (/:locale)/orders(.:format)                  orders#index
#                    POST   (/:locale)/orders(.:format)                  orders#create
#          new_order GET    (/:locale)/orders/new(.:format)              orders#new
#         edit_order GET    (/:locale)/orders/:id/edit(.:format)         orders#edit
#              order GET    (/:locale)/orders/:id(.:format)              orders#show
#                    PATCH  (/:locale)/orders/:id(.:format)              orders#update
#                    PUT    (/:locale)/orders/:id(.:format)              orders#update
#                    DELETE (/:locale)/orders/:id(.:format)              orders#destroy
#         line_items GET    (/:locale)/line_items(.:format)              line_items#index
#                    POST   (/:locale)/line_items(.:format)              line_items#create
#      new_line_item GET    (/:locale)/line_items/new(.:format)          line_items#new
#     edit_line_item GET    (/:locale)/line_items/:id/edit(.:format)     line_items#edit
#          line_item GET    (/:locale)/line_items/:id(.:format)          line_items#show
#                    PATCH  (/:locale)/line_items/:id(.:format)          line_items#update
#                    PUT    (/:locale)/line_items/:id(.:format)          line_items#update
#                    DELETE (/:locale)/line_items/:id(.:format)          line_items#destroy
#              carts GET    (/:locale)/carts(.:format)                   carts#index
#                    POST   (/:locale)/carts(.:format)                   carts#create
#           new_cart GET    (/:locale)/carts/new(.:format)               carts#new
#          edit_cart GET    (/:locale)/carts/:id/edit(.:format)          carts#edit
#               cart GET    (/:locale)/carts/:id(.:format)               carts#show
#                    PATCH  (/:locale)/carts/:id(.:format)               carts#update
#                    PUT    (/:locale)/carts/:id(.:format)               carts#update
#                    DELETE (/:locale)/carts/:id(.:format)               carts#destroy
# who_bought_product GET    (/:locale)/products/:id/who_bought(.:format) products#who_bought
#           products GET    (/:locale)/products(.:format)                products#index
#                    POST   (/:locale)/products(.:format)                products#create
#        new_product GET    (/:locale)/products/new(.:format)            products#new
#       edit_product GET    (/:locale)/products/:id/edit(.:format)       products#edit
#            product GET    (/:locale)/products/:id(.:format)            products#show
#                    PATCH  (/:locale)/products/:id(.:format)            products#update
#                    PUT    (/:locale)/products/:id(.:format)            products#update
#                    DELETE (/:locale)/products/:id(.:format)            products#destroy
#        store_index GET    (/:locale)/store/index(.:format)             store#index
#              store GET    /(:locale)(.:format)                         store#index
#

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="store">
    <div id="banner">
      <%= form_tag store_index_path, method: :get, class: "locale" do %>
        <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>

      <%= link_to image_tag('logo.png'), store_path %>
      <%= @page_title || t('.title') %>
    </div>
    <div id="columns">
      <div id="side">
        <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, :id => 'cart') do %>
            <%= render @cart %>
          <% end %>
        <% end %>

        <%= link_to t('.home'), store_path %> <br>
        <%= link_to t('.questions'), '#' %> <br>
        <%= link_to t('.news'), '#' %> <br>
        <%= link_to t('.contact'), '#' %> <br>

        <% if session[:user_id] %>
          <br>
          <%= link_to 'Orders', orders_path %> <br>
          <%= link_to 'Products', products_path %> <br>
          <%= link_to 'Users', users_path %> <br>
          <br>
          <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>

        <span class="datetime"><%= Time.now.to_s(:long) %></span>
      </div>
      <div id="main">
        <% if notice %>
          <p id="notice"><%= notice %></p>
        <% end %>

        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>